// Generated by scripts/process-media.mjs. Do not edit by hand.
export const media = {
  "plane-spotter-board": {
    "width": 1600,
    "height": 1000,
    "widths": [
      720,
      1100,
      1600
    ]
  },
  "panmilli-products": {
    "width": 1600,
    "height": 1000,
    "widths": [
      720,
      1100,
      1600
    ]
  },
  "eshee-esthetic": {
    "width": 1600,
    "height": 1000,
    "widths": [
      720,
      1100,
      1600
    ]
  },
  "hero-toronto-dusk": {
    "width": 1600,
    "height": 900,
    "widths": [
      720,
      1100,
      1600
    ]
  },
  "an225-yyz": {
    "width": 1600,
    "height": 640,
    "widths": [
      720,
      1100,
      1600
    ]
  },
  "klm-747-approach": {
    "width": 1400,
    "height": 871,
    "widths": [
      640,
      1000,
      1400
    ]
  },
  "klm-747-overhead": {
    "width": 1400,
    "height": 886,
    "widths": [
      640,
      1000,
      1400
    ]
  },
  "klm-747-touchdown": {
    "width": 2000,
    "height": 778,
    "widths": [
      640,
      1000,
      1400,
      2000
    ]
  },
  "ac-787-c-fksv": {
    "width": 1100,
    "height": 1673,
    "widths": [
      480,
      800,
      1100
    ]
  }
} as const satisfies Record<
  string,
  { width: number; height: number; widths: readonly number[] }
>;

export type MediaId = keyof typeof media;
