// Turns originals in media-src/ (not committed: they are large, and the phone
// shots carry GPS) into the web-ready files in public/media/, and writes
// src/content/media.generated.ts so every <img> gets its real width/height.
//
//   npm run media            images and video
//   npm run media -- images  images only
//
// sharp drops all EXIF/XMP/GPS metadata unless asked to keep it, which is what
// we want for anything published.
import sharp from 'sharp';
import ffmpegPath from 'ffmpeg-static';
import { execFileSync } from 'node:child_process';
import { mkdir, writeFile, stat } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const root = (p) => fileURLToPath(new URL(`../${p}`, import.meta.url));
const SRC = root('media-src/');
const OUT = root('public/media/');
const MANIFEST = root('src/content/media.generated.ts');

/**
 * crop: fractions of the source (after EXIF rotation), so they survive a
 * re-export of the original at a different resolution.
 */
const images = [
  { id: 'plane-spotter-board', src: 'plane-spotter-board.png', widths: [720, 1100, 1600] },
  { id: 'panmilli-products', src: 'panmilli-products.png', widths: [720, 1100, 1600] },
  { id: 'eshee-esthetic', src: 'eshee-esthetic.png', widths: [720, 1100, 1600] },
  // Home hero. AI-generated illustration, not a photograph: labelled as such
  // in its alt text, and never shown among my photographs.
  { id: 'hero-toronto-dusk', src: 'hero-toronto-dusk.png', widths: [720, 1100, 1600] },
  {
    id: 'an225-yyz',
    src: 'an225-yyz-2020-05-31.jpg',
    // Trim empty sky and the nearest row of parked cars.
    crop: { left: 0, top: 0.24, width: 1, height: 0.6 },
    widths: [720, 1100, 1600],
  },
  { id: 'klm-747-approach', src: 'klm-747-approach.jpg', widths: [640, 1000, 1400] },
  { id: 'klm-747-overhead', src: 'klm-747-overhead.jpg', widths: [640, 1000, 1400] },
  // Also the Spotting banner, shown up to 76rem wide: needs a 2x size.
  { id: 'klm-747-touchdown', src: 'klm-747-touchdown.jpg', widths: [640, 1000, 1400, 2000] },
  { id: 'ac-787-c-fksv', src: 'ac-787-c-fksv.jpg', widths: [480, 800, 1100] },
];

/**
 * Clips are re-encoded to the budget in SPEC §11: H.264, ≤1080p, 30fps.
 * Audio is dropped: it is wind and engine noise, and a silent clip needs no
 * captions and costs nothing to decode.
 */
const clips = [
  {
    id: 'lh-747-landing',
    src: 'lh-747-landing.mp4',
    // Shot at 120fps; replay at half speed so the 30fps output keeps detail.
    start: 0,
    duration: 12,
    filter: 'setpts=2.0*PTS,fps=30',
    posterAt: 2.6,
  },
  {
    id: 'widebody-overhead',
    src: 'widebody-overhead.mp4',
    start: 0,
    duration: 12,
    filter: 'fps=30',
    posterAt: 7,
  },
];

const only = process.argv[2];
await mkdir(OUT, { recursive: true });

const manifest = {};

if (!only || only === 'images') {
  for (const image of images) {
    let pipeline = sharp(SRC + image.src).rotate();
    const meta = await pipeline.metadata();
    // metadata() reports pre-rotation dimensions; orientations 5–8 swap axes.
    const swap = (meta.orientation ?? 1) >= 5;
    let width = swap ? meta.height : meta.width;
    let height = swap ? meta.width : meta.height;

    if (image.crop) {
      const region = {
        left: Math.round(image.crop.left * width),
        top: Math.round(image.crop.top * height),
        width: Math.round(image.crop.width * width),
        height: Math.round(image.crop.height * height),
      };
      pipeline = sharp(await pipeline.extract(region).toBuffer());
      width = region.width;
      height = region.height;
    } else {
      pipeline = sharp(await pipeline.toBuffer());
    }

    const widths = image.widths.filter((w) => w <= width);
    for (const w of widths) {
      const resized = pipeline.clone().resize({ width: w });
      await resized.clone().avif({ quality: 52, effort: 6 }).toFile(`${OUT}${image.id}-${w}.avif`);
      await resized
        .clone()
        .jpeg({ quality: 74, mozjpeg: true, progressive: true })
        .toFile(`${OUT}${image.id}-${w}.jpg`);
    }
    const largest = widths.at(-1);
    manifest[image.id] = {
      width: largest,
      height: Math.round((height / width) * largest),
      widths,
    };
    console.log(`image ${image.id}: ${widths.join(', ')}`);
  }

  const body = `// Generated by scripts/process-media.mjs. Do not edit by hand.
export const media = ${JSON.stringify(manifest, null, 2)} as const satisfies Record<
  string,
  { width: number; height: number; widths: readonly number[] }
>;

export type MediaId = keyof typeof media;
`;
  await writeFile(MANIFEST, body);
}

if (!only || only === 'video') {
  for (const clip of clips) {
    const input = SRC + clip.src;
    const output = `${OUT}${clip.id}.mp4`;
    // -threads 1: the static ffmpeg build runs out of address space on some
    // Windows machines with frame threading on 120fps sources.
    execFileSync(ffmpegPath, [
      '-v', 'error', '-y', '-threads', '1',
      '-ss', String(clip.start), '-t', String(clip.duration), '-i', input,
      '-an',
      '-vf', `${clip.filter},scale=-2:720:out_range=tv,format=yuv420p`,
      '-c:v', 'libx264', '-preset', 'slow', '-crf', '27', '-profile:v', 'high',
      '-maxrate', '2M', '-bufsize', '4M',
      '-movflags', '+faststart', '-map_metadata', '-1',
      output,
    ]);
    const poster = sharp(
      execFileSync(ffmpegPath, [
        '-v', 'error', '-threads', '1', '-ss', String(clip.posterAt), '-i', input,
        '-frames:v', '1', '-f', 'image2pipe', '-vcodec', 'png', '-',
      ], { maxBuffer: 64 * 1024 * 1024 }),
    ).resize({ width: 960 });
    // Posters download even with preload="none", so keep them light.
    await poster.clone().jpeg({ quality: 66, mozjpeg: true }).toFile(`${OUT}${clip.id}-poster.jpg`);
    const { size } = await stat(output);
    console.log(`clip ${clip.id}: ${(size / 1024 / 1024).toFixed(2)} MB`);
  }
}
